version: "3"

services:

  runtime-setup:
    image: netty:panama
    build:
      dockerfile: Dockerfile.panama_foreign

  build:
    image: netty:panama

  build-leak:
    image: netty:panama
    command: '/bin/bash -cl "
      ./mvnw -B -ntp clean install -DskipTests -Pfast &&
      ./mvnw -B -ntp -Pleak verify -Dio.netty5.testsuite.badHost=netty.io -Dtcnative.classifier=linux-x86_64-fedora -pl buffer-memory-segment
    "'

  build-boringssl-static:
    image: netty:panama

  build-leak-boringssl-static:
    image: netty:panama

  build-unsafe-buffer:
    image: netty:panama

  stage-snapshot:
    image: netty:panama

  stage-release:
    image: netty:panama

  deploy:
    image: netty:panama

  shell:
    image: netty:panama
